In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
from torchvision import models,transforms
from torchvision.utils import make_grid
from torchvision.datasets import MNIST
from torch.utils.data.sampler import SubsetRandomSampler
from torch.utils.tensorboard import SummaryWriter
from torchsummary import summary
from torch.utils.data import Dataset, DataLoader

In [24]:
class Dropout_Demo(nn.Module):
  def __init__(self):
    super().__init__()
    self.dropout_layer = nn.Dropout(0.7)


  def forward(self, x):
    x = self.dropout_layer(x)
    return x




In [25]:
dropout_model = Dropout_Demo()
toy_data = torch.ones([1,10]).float()
toy_data

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
dropout_model.train()
dropout_model(toy_data)

tensor([[3.3333, 0.0000, 0.0000, 0.0000, 0.0000, 3.3333, 0.0000, 3.3333, 3.3333,
         0.0000]])

In [17]:
dropout_model.eval()
dropout_model(toy_data)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])